# Site settings
title: "Somewhat Related"
description: "Tangential technology talk."
podcast-description: >
  Our entry into the two dudes talking podcast genre from two technology fanatics. We use tech news as a springboard into deep exploration of topics, issues, and anecdotes.
  
  Embrace the tangent.
url: "https://dotrun.github.io/somewhatrelated.fm" # Actual base url of the website
baseurl: "" # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "dotRun"
  email: "company@dotrun.io"
  url: "https://dotrun.io"

permalink: /:year/:month/:day/:title/
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: SomewhatRelated
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Somewhat Related
  links:
    - https://twitter.com/SomewhatRelated
lang: en

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Somewhat Related
podcast_author: Taylor Becker
podcast_email: taylor.becker@dotrun.io
podcast_subtitle: "Tangential technology talk."
podcast_summary: ""
podcast_description: ""
podcast_explicit: "no"
podcast_type: episo 
podcast_lang: en
podcast_launch: "2022-07-04" #Launch date of your podcast
podcast_copyright: "&#xA9;dotRun LLC"
podcast_feed: episodic
podcast_artwork: "/assets/img/Podcast_Cover.png"